### ISSUE TITLE
[BUG] PageVerification: Always turns to green if no verification data is present due to boolean answer of the external verifier

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/data-accounting-external-verifier#5]
Resolve: Return status code e.g.: Verified / Failed / MissingVerificationData

**Comment by rht** [comment]
Fixed in https://github.com/FantasticoFox/data-accounting-external-verifier/commit/4e2fe1a75ff3da153516fd403dbdb087fe2b3ec6.
